import { describe, it, expect } from "vitest";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parse23andMe } from "../src/parsers/twentythree-and-me.js";
import { parseAncestryDNA } from "../src/parsers/ancestrydna.js";
import { detectFormat } from "../src/parsers/index.js";

const TMP = join(tmpdir(), "genomic-report-tests");
try { mkdirSync(TMP, { recursive: true }); } catch {}

const SAMPLE_23ANDME = `# This data file generated by 23andMe at: Tue Oct 25 11:21:31 2022
#
# Below is a text version of your data.  Fields are TAB-separated
# We are using reference human assembly build 37 (also known as Annotation Release 104).
#
# rsid\tchromosome\tposition\tgenotype
rs548049170\t1\t69869\tTT
rs9326622\t1\t567092\tCC
rs429358\t19\t45411941\tTT
rs7412\t19\t45412079\tCC
rs1799853\t10\t96702047\tCT
rs4680\t22\t19951271\tAA
`;

const SAMPLE_ANCESTRY = `#AncestryDNA raw data download
#This file was generated by AncestryDNA
rsid\tchromosome\tposition\tallele1\tallele2
rs548049170\t1\t69869\tT\tT
rs9326622\t1\t567092\tC\tC
rs429358\t19\t45411941\tT\tT
rs7412\t19\t45412079\tC\tC
rs4680\t22\t19951271\tA\tA
`;

describe("23andMe parser", () => {
  it("parses a valid 23andMe file", () => {
    const path = join(TMP, "test-23andme.txt");
    writeFileSync(path, SAMPLE_23ANDME);

    const result = parse23andMe(path);

    expect(result.format).toBe("23andme");
    expect(result.buildVersion).toBe("GRCh37");
    expect(result.totalSnps).toBe(6);
    expect(result.snps.has("rs429358")).toBe(true);
    expect(result.snps.get("rs429358")?.genotype).toBe("TT");
    expect(result.snps.get("rs4680")?.genotype).toBe("AA");
    expect(result.snps.get("rs1799853")?.chromosome).toBe("10");
  });

  it("extracts generation date from metadata", () => {
    const path = join(TMP, "test-23andme-meta.txt");
    writeFileSync(path, SAMPLE_23ANDME);

    const result = parse23andMe(path);
    expect(result.metadata.generatedAt).toContain("Tue Oct 25");
  });

  it("skips comment and empty lines", () => {
    const data = `# comment\n\n# another comment\nrs123\t1\t100\tAG\n`;
    const path = join(TMP, "test-23andme-skip.txt");
    writeFileSync(path, data);

    const result = parse23andMe(path);
    expect(result.totalSnps).toBe(1);
  });
});

describe("AncestryDNA parser", () => {
  it("parses a valid AncestryDNA file", () => {
    const path = join(TMP, "test-ancestry.txt");
    writeFileSync(path, SAMPLE_ANCESTRY);

    const result = parseAncestryDNA(path);

    expect(result.format).toBe("ancestrydna");
    expect(result.totalSnps).toBe(5);
    expect(result.snps.get("rs429358")?.genotype).toBe("TT");
    expect(result.snps.get("rs4680")?.genotype).toBe("AA");
  });

  it("skips no-call genotypes (0/0)", () => {
    const data = `#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\nrs111\t1\t100\t0\t0\nrs222\t1\t200\tA\tG\n`;
    const path = join(TMP, "test-ancestry-nocall.txt");
    writeFileSync(path, data);

    const result = parseAncestryDNA(path);
    expect(result.totalSnps).toBe(1);
    expect(result.snps.has("rs111")).toBe(false);
  });
});

describe("Format auto-detection", () => {
  it("detects 23andMe format", () => {
    const path = join(TMP, "detect-23.txt");
    writeFileSync(path, SAMPLE_23ANDME);
    expect(detectFormat(path)).toBe("23andme");
  });

  it("detects AncestryDNA format", () => {
    const path = join(TMP, "detect-anc.txt");
    writeFileSync(path, SAMPLE_ANCESTRY);
    expect(detectFormat(path)).toBe("ancestrydna");
  });

  it("detects VCF format", () => {
    const path = join(TMP, "detect-vcf.txt");
    writeFileSync(path, "##fileformat=VCFv4.1\n##INFO=<ID=NS>\n#CHROM\tPOS\n");
    expect(detectFormat(path)).toBe("vcf");
  });
});
