import { readFileSync } from "node:fs";
import type { InputFormat, ParsedGenome, RawGenotype } from "../types.js";

/**
 * Parse a 23andMe raw data file (v4/v5).
 *
 * Format:
 *   # comment lines
 *   rsid \t chromosome \t position \t genotype
 *
 * Handles both Unix and Windows line endings.
 */
export function parse23andMe(filePath: string): ParsedGenome {
  const raw = readFileSync(filePath, "utf-8");
  const lines = raw.split(/\r?\n/);

  const metadata: Record<string, string> = {};
  const snps = new Map<string, RawGenotype>();
  let buildVersion = "GRCh37"; // 23andMe default

  for (const line of lines) {
    // Extract metadata from comment lines
    if (line.startsWith("#")) {
      if (line.includes("build 37")) buildVersion = "GRCh37";
      if (line.includes("build 38")) buildVersion = "GRCh38";
      if (line.includes("generated by")) {
        const match = line.match(/generated by 23andMe at: (.+)/);
        if (match) metadata.generatedAt = match[1].trim();
      }
      continue;
    }

    if (!line.trim()) continue;

    const parts = line.split("\t");
    if (parts.length < 4) continue;

    const [rsid, chromosome, posStr, genotype] = parts;

    // Skip internal IDs (not rs-prefixed) unless they look like "i" IDs
    // We keep everything — users may want to look up internal IDs later
    const position = parseInt(posStr, 10);
    if (isNaN(position)) continue;

    snps.set(rsid, {
      rsid,
      chromosome,
      position,
      genotype: genotype.trim(),
    });
  }

  return {
    format: "23andme" as InputFormat,
    buildVersion,
    totalSnps: snps.size,
    snps,
    metadata,
  };
}
