import type { PathwayDefinition } from "../types.js";

/**
 * Biological pathway definitions for clustering genomic variants.
 *
 * Each pathway defines matching criteria (genes, keywords, categories, tags),
 * synergy parameters, gene-gene interaction notes, and narrative templates.
 */
export const PATHWAY_DEFINITIONS: PathwayDefinition[] = [
  // ─── Cardiovascular ─────────────────────────────────────────
  {
    name: "Coronary Artery Disease / Atherosclerosis",
    slug: "cad",
    description: "Variants affecting arterial plaque formation, lipid metabolism, and vascular inflammation that converge on coronary artery disease risk.",
    genePatterns: ["9p21", "SORT1", "PCSK9", "LDLR", "LPA", "CXCL12", "MIA3", "WDR12", "MTHFD1L"],
    keywords: ["coronary", "cad", "ldl", "cholesterol", "atherosclerosis", "myocardial", "9p21"],
    categories: ["cardiovascular"],
    tags: ["pathway:cad"],
    interactionNotes: {
      "PCSK9+LDLR": "PCSK9 regulates LDLR degradation — variants in both genes compound LDL clearance impairment.",
      "LPA+9p21": "Elevated Lp(a) combined with 9p21 risk amplifies atherosclerotic burden beyond additive effects.",
      "SORT1+LDLR": "SORT1 affects hepatic VLDL secretion while LDLR handles uptake — dual impairment disrupts lipid homeostasis.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.5,
    narrativeTemplate: "This individual carries {{variantCount}} variant(s) affecting coronary artery disease pathways ({{geneList}}), with {{homCount}} in homozygous state. {{compoundEffects}}The compound pathway score is {{synergyScore}}/100, suggesting {{riskLabel}} cardiovascular risk. Comprehensive lipid panel including Lp(a) and apoB is warranted.",
    actionTemplates: [
      {
        priority: "urgent",
        category: "screening",
        title: "Coronary artery calcium (CAC) score",
        detail: "Multiple CAD-related risk variants identified. Comprehensive lipid panel with Lp(a) and apoB also recommended.",
        minRiskLevel: "elevated",
      },
      {
        priority: "recommended",
        category: "lifestyle",
        title: "Mediterranean diet and regular aerobic exercise",
        detail: "Genetic CAD risk can be substantially mitigated by lifestyle. Target 150min/week moderate-intensity exercise.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Atrial Fibrillation",
    slug: "af",
    description: "Variants in cardiac ion channels and transcription factors that increase susceptibility to atrial fibrillation.",
    genePatterns: ["PITX2", "4q25", "KCNN3", "ZFHX3", "KCNA5", "SCN5A", "SCN10A"],
    keywords: ["atrial fibrillation"],
    categories: [],
    tags: ["pathway:af"],
    interactionNotes: {
      "PITX2+KCNN3": "PITX2 regulates atrial development while KCNN3 modulates calcium-activated potassium currents — co-occurrence increases arrhythmogenic substrate.",
    },
    synergyMultiplier: 1.4,
    homozygousPenalty: 1.6,
    narrativeTemplate: "{{variantCount}} variant(s) affecting atrial fibrillation susceptibility were identified ({{geneList}}), with {{homCount}} homozygous. {{compoundEffects}}Pathway score: {{synergyScore}}/100, indicating {{riskLabel}} AF risk. Baseline ECG and awareness of palpitation symptoms recommended.",
    actionTemplates: [
      {
        priority: "urgent",
        category: "screening",
        title: "Baseline ECG and consider Holter monitoring",
        detail: "Elevated genetic AF risk. Alert for palpitations, irregular pulse. Moderate alcohol and caffeine.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "Lipid Metabolism",
    slug: "lipid-metabolism",
    description: "Variants across the lipid transport and metabolism cascade — from hepatic synthesis through circulating lipoproteins to peripheral uptake.",
    genePatterns: ["PCSK9", "CETP", "LDLR", "APOB", "LPA", "APOE", "APOA1", "LIPC", "LPL", "ANGPTL3"],
    keywords: ["lipid", "ldl", "hdl", "triglyceride", "cholesterol", "hyperlipidemia", "dyslipidemia"],
    categories: [],
    tags: ["pathway:lipid-metabolism"],
    interactionNotes: {
      "CETP+LDLR": "CETP mediates HDL-LDL cholesterol transfer while LDLR clears LDL — variants in both disrupt the entire cholesterol shuttle.",
      "PCSK9+APOB": "PCSK9 degrades LDLR while APOB variants alter LDL particle composition — compound effect on circulating LDL concentration.",
      "LPA+APOB": "Elevated Lp(a) plus altered apoB increases atherogenic particle count synergistically.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} variant(s) span the lipid metabolism cascade ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on lipoprotein homeostasis.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Advanced lipid panel with particle size analysis",
        detail: "Multiple lipid pathway variants warrant detailed lipid subfractionation beyond standard panel.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Coagulation Cascade",
    slug: "coagulation",
    description: "Variants in clotting factors, platelet receptors, and fibrinolysis that affect thrombotic risk.",
    genePatterns: ["F5", "F2", "F7", "F11", "F12", "F13", "ITGA2B", "ITGB3", "VWF", "SERPINE1", "GP1BA", "PROC", "PROS1"],
    keywords: ["thrombosis", "clotting", "coagulation", "factor v", "prothrombin", "dvt", "embolism", "fibrinogen"],
    categories: ["hematological"],
    tags: ["pathway:coagulation"],
    interactionNotes: {
      "F5+F2": "Factor V Leiden combined with prothrombin G20210A dramatically increases VTE risk — estimated 20-50x for double heterozygotes.",
      "F5+SERPINE1": "Factor V Leiden with elevated PAI-1 compounds clot persistence through impaired fibrinolysis.",
    },
    synergyMultiplier: 1.5,
    homozygousPenalty: 2.0,
    narrativeTemplate: "{{variantCount}} coagulation pathway variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} thrombotic risk. Discuss with haematologist, especially before surgery or hormonal therapy.",
    actionTemplates: [
      {
        priority: "urgent",
        category: "screening",
        title: "Haematology consultation for thrombophilia",
        detail: "Multiple coagulation variants warrant specialist review, especially for surgical planning and contraceptive choices.",
        minRiskLevel: "elevated",
      },
    ],
  },

  // ─── Metabolic ──────────────────────────────────────────────
  {
    name: "Type 2 Diabetes / Metabolic Syndrome",
    slug: "t2d",
    description: "Variants affecting insulin secretion, glucose sensing, and adiposity that converge on metabolic syndrome risk.",
    genePatterns: ["TCF7L2", "FTO", "MC4R", "KCNJ11", "PPARG", "SLC30A8", "CDKAL1", "IGF2BP2", "HHEX", "CDKN2A"],
    keywords: ["diabetes", "obesity", "bmi", "insulin", "metabolic", "glucose"],
    categories: ["metabolic"],
    tags: ["pathway:t2d"],
    interactionNotes: {
      "TCF7L2+KCNJ11": "TCF7L2 affects incretin signalling while KCNJ11 controls beta-cell KATP channels — combined variants impair both insulin secretion pathways.",
      "FTO+MC4R": "FTO drives adiposity via appetite regulation; MC4R controls satiety signalling — compound effect on energy balance.",
      "TCF7L2+SLC30A8": "Both affect beta-cell zinc transport and insulin crystallisation — synergistic impairment of insulin packaging.",
    },
    synergyMultiplier: 1.25,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} variant(s) affecting glucose metabolism and insulin signalling ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100, suggesting {{riskLabel}} metabolic risk. Regular HbA1c monitoring recommended.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Fasting glucose and HbA1c",
        detail: "Multiple T2D-related risk variants. Monitor metabolic markers regularly.",
        minRiskLevel: "elevated",
      },
      {
        priority: "consider",
        category: "lifestyle",
        title: "Glycaemic index-aware diet",
        detail: "Genetic insulin sensitivity variants respond well to low-GI dietary patterns.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Iron Metabolism",
    slug: "iron-metabolism",
    description: "Variants in iron absorption, transport, and regulatory proteins that affect iron homeostasis and haemochromatosis risk.",
    genePatterns: ["HFE", "TFR2", "HAMP", "SLC40A1", "HJV", "BMP6", "TMPRSS6"],
    keywords: ["haemochromatosis", "hemochromatosis", "iron overload", "iron deficiency", "ferritin", "transferrin"],
    categories: [],
    tags: ["pathway:iron-metabolism"],
    interactionNotes: {
      "HFE+TFR2": "Both regulate hepcidin expression — compound variants can cause severe hereditary haemochromatosis.",
      "HFE+TMPRSS6": "TMPRSS6 cleaves hemojuvelin to suppress hepcidin; HFE mutations reduce hepcidin — additive iron overload risk.",
    },
    synergyMultiplier: 1.4,
    homozygousPenalty: 1.8,
    narrativeTemplate: "{{variantCount}} iron metabolism variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} risk of iron dysregulation. Serum ferritin and transferrin saturation testing recommended.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Iron studies panel",
        detail: "Check serum ferritin, transferrin saturation, and TIBC. Repeat annually if elevated.",
        minRiskLevel: "moderate",
      },
    ],
  },

  // ─── Immune / Inflammatory ──────────────────────────────────
  {
    name: "NF-κB Signaling",
    slug: "nfkb",
    description: "Variants in the NF-κB inflammatory signalling cascade — from pattern recognition receptors through adaptor proteins to transcription factor activation.",
    genePatterns: ["MYD88", "NOD2", "CD40", "TLR", "TRAF", "NFKB", "IRAK", "IKBK", "REL", "TNFAIP3", "TNIP1"],
    keywords: ["nf-kb", "nfkb", "inflammatory", "innate immune", "toll-like"],
    categories: [],
    tags: ["pathway:nfkb"],
    interactionNotes: {
      "NOD2+MYD88": "NOD2 senses muramyl dipeptide while MYD88 adapts TLR signals — dual pathway activation drives excessive NF-κB-mediated inflammation.",
      "TLR+TNFAIP3": "TLR variants increase NF-κB activation while TNFAIP3 (A20) variants impair its negative regulation — synergistic inflammatory amplification.",
      "NOD2+TLR": "Convergent activation of NF-κB through both intracellular and surface pattern recognition compounds inflammatory signalling.",
    },
    synergyMultiplier: 1.4,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} variant(s) in the NF-κB signalling cascade ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} inflammatory signalling dysregulation. This pathway is central to autoimmune and chronic inflammatory conditions.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "monitoring",
        title: "Inflammatory marker panel (hs-CRP, ESR, IL-6)",
        detail: "NF-κB pathway variants may drive chronic subclinical inflammation. Baseline inflammatory markers recommended.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "Autoimmune HLA Cluster",
    slug: "autoimmune-hla",
    description: "Variants in HLA antigen presentation, T-cell co-stimulation, and immune checkpoint genes that synergistically increase autoimmune susceptibility.",
    genePatterns: ["HLA-", "CTLA4", "PTPN22", "IL2RA", "IL23R", "IL10", "ATG16L1", "STAT4", "IRF5", "TNFRSF1A"],
    keywords: ["autoimmune", "rheumatoid", "crohn", "celiac", "psoriasis", "lupus", "inflammatory bowel"],
    categories: ["autoimmune"],
    tags: ["pathway:autoimmune-hla"],
    interactionNotes: {
      "HLA-+CTLA4": "HLA variants alter antigen presentation specificity while CTLA4 variants impair T-cell inhibition — together they compound autoimmune risk by presenting self-antigens without adequate T-cell braking.",
      "HLA-+PTPN22": "PTPN22 R620W reduces T-cell receptor threshold; combined with HLA risk alleles, self-reactive T-cells are more easily activated.",
      "CTLA4+IL2RA": "Both regulate T-cell activation checkpoints — compound variants remove multiple layers of immune tolerance.",
      "HLA-+IL23R": "HLA variants determine antigen presentation; IL-23R drives Th17 differentiation — synergistic pathway to Th17-mediated autoimmunity.",
      "PTPN22+IL2RA": "PTPN22 lowers T-cell activation threshold while IL2RA variants impair Treg function — dual failure of immune tolerance.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} variant(s) across the autoimmune susceptibility cluster ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} autoimmune risk. The combination of antigen presentation (HLA), co-stimulation (CTLA4), and signalling (IL/STAT) variants reveals synergistic immune dysregulation.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "monitoring",
        title: "Monitor for autoimmune symptoms",
        detail: "High autoimmune genetic loading. Anti-CCP/RF if joint symptoms; GI workup if IBD symptoms; ANA panel if multi-system.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "JAK-STAT Signaling",
    slug: "jak-stat",
    description: "Variants in the Janus kinase / signal transducer and activator of transcription pathway, central to cytokine signalling and immune regulation.",
    genePatterns: ["JAK1", "JAK2", "JAK3", "TYK2", "STAT1", "STAT2", "STAT3", "STAT4", "STAT5", "STAT6", "IL2RA", "IL23R", "IL10", "IL6", "IL12", "IFNAR"],
    keywords: ["jak-stat", "cytokine", "interleukin signaling"],
    categories: [],
    tags: ["pathway:jak-stat"],
    interactionNotes: {
      "STAT4+IL23R": "STAT4 mediates IL-12 signalling for Th1 cells while IL-23R drives Th17 — combined variants skew both T-helper lineages toward autoimmunity.",
      "JAK2+STAT3": "JAK2 activates STAT3 directly — variants in both amplify downstream oncogenic and inflammatory transcription.",
      "IL2RA+IL10": "IL-2R drives T-cell expansion while IL-10 controls anti-inflammatory feedback — compound variants create immune activation without adequate regulation.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} JAK-STAT pathway variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on cytokine signalling. This pathway is targetable by JAK inhibitors if clinically relevant.",
    actionTemplates: [
      {
        priority: "consider",
        category: "monitoring",
        title: "Cytokine panel if symptomatic",
        detail: "JAK-STAT variants may respond to targeted therapy. Discuss with rheumatologist or immunologist if autoimmune symptoms develop.",
        minRiskLevel: "elevated",
      },
    ],
  },

  // ─── Methylation & Detox ────────────────────────────────────
  {
    name: "Methylation Cycle",
    slug: "methylation",
    description: "Variants in one-carbon metabolism affecting folate cycling, homocysteine clearance, and methylation capacity — with downstream effects on DNA repair, neurotransmitter synthesis, and detoxification.",
    genePatterns: ["MTHFR", "MTR", "MTRR", "COMT", "DHFR", "MAT1A", "BHMT", "CBS", "AHCY", "SHMT"],
    keywords: ["folate", "methylation", "homocysteine", "mthfr", "methionine", "one-carbon"],
    categories: ["nutrigenomic"],
    tags: ["pathway:methylation"],
    interactionNotes: {
      "MTHFR+COMT": "Reduced methylation from MTHFR impairs COMT function, compounding catecholamine clearance and increasing dopamine/norepinephrine levels.",
      "MTHFR+MTR": "MTHFR converts folate to methylfolate; MTR uses it to remethylate homocysteine — compound variants severely impair the methylation cycle.",
      "MTHFR+MTRR": "MTRR regenerates MTR (methionine synthase) — with MTHFR variants limiting methylfolate supply, MTRR variants further reduce homocysteine clearance.",
      "CBS+BHMT": "Both provide alternative homocysteine disposal routes — compound variants leave MTHFR-dependent remethylation as the sole pathway.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.6,
    narrativeTemplate: "{{variantCount}} variant(s) in the methylation/one-carbon cycle ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on methylation capacity. Consider homocysteine levels and methylfolate supplementation.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Serum homocysteine and folate levels",
        detail: "Methylation cycle variants may elevate homocysteine. Methylfolate (not folic acid) may be preferred supplementation.",
        minRiskLevel: "moderate",
      },
      {
        priority: "consider",
        category: "supplement",
        title: "Methylfolate over folic acid",
        detail: "MTHFR variants reduce folic acid conversion. Active methylfolate bypasses this bottleneck.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Oxidative Stress Response",
    slug: "oxidative-stress",
    description: "Variants in antioxidant enzymes and oxidative damage repair that affect cellular defence against reactive oxygen species.",
    genePatterns: ["SOD2", "SOD1", "SOD3", "GSTP1", "GSTM1", "GSTT1", "NQO1", "CAT", "GPX1", "NFE2L2", "HMOX1"],
    keywords: ["oxidative stress", "antioxidant", "reactive oxygen", "free radical", "glutathione"],
    categories: [],
    tags: ["pathway:oxidative-stress"],
    interactionNotes: {
      "SOD2+GSTP1": "SOD2 converts superoxide to H2O2; GSTP1 conjugates reactive metabolites — compound variants impair both primary and secondary antioxidant defence.",
      "SOD2+CAT": "SOD2 produces H2O2 from superoxide; catalase breaks down H2O2 — if both are impaired, H2O2 accumulates causing oxidative damage.",
      "NQO1+GSTP1": "NQO1 reduces quinones; GSTP1 conjugates electrophiles — compound variants reduce Phase I + Phase II detox of oxidative metabolites.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} oxidative stress pathway variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} antioxidant capacity. Consider antioxidant-rich diet and targeted supplementation.",
    actionTemplates: [
      {
        priority: "consider",
        category: "supplement",
        title: "Antioxidant support evaluation",
        detail: "Consider glutathione precursors (NAC), CoQ10, and dietary polyphenols based on specific variant profile.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Catecholamine Metabolism",
    slug: "catecholamine",
    description: "Variants in enzymes that synthesise, transport, and degrade catecholamines (dopamine, norepinephrine, epinephrine) — affecting mood, cognition, and stress response.",
    genePatterns: ["COMT", "MAOA", "MAOB", "DBH", "DDC", "TH", "SLC6A3", "SLC6A4", "PNMT"],
    keywords: ["catecholamine", "dopamine", "serotonin", "norepinephrine", "monoamine"],
    categories: ["psychiatric"],
    tags: ["pathway:catecholamine"],
    interactionNotes: {
      "COMT+MAOA": "COMT and MAO-A are the two primary catecholamine degradation enzymes — compound slow variants dramatically increase synaptic catecholamine levels.",
      "COMT+SLC6A3": "COMT degrades dopamine while DAT (SLC6A3) recycles it — compound variants alter dopaminergic tone bidirectionally.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} catecholamine metabolism variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on neurotransmitter balance. May affect stress resilience, mood regulation, and stimulant sensitivity.",
    actionTemplates: [
      {
        priority: "consider",
        category: "lifestyle",
        title: "Stress management and stimulant awareness",
        detail: "Catecholamine pathway variants may increase sensitivity to caffeine, stimulants, and psychological stress.",
        minRiskLevel: "moderate",
      },
    ],
  },

  // ─── Psychiatric (PGC GWAS) ────────────────────────────────
  {
    name: "Glutamatergic Signaling",
    slug: "glutamate",
    description: "Variants in glutamate receptors and calcium channels affecting excitatory neurotransmission — implicated in schizophrenia, bipolar disorder, and depression.",
    genePatterns: ["GRIN2A", "GRIN2B", "GRM3", "GRM5", "GRIA1", "SRR", "CACNA1C", "CACNB2", "CLCN3"],
    keywords: ["glutamate", "nmda", "calcium channel", "excitatory", "ionotropic"],
    categories: ["psychiatric"],
    tags: ["pathway:glutamate"],
    interactionNotes: {
      "GRIN2A+CACNA1C": "NMDA receptors and L-type calcium channels are both voltage-dependent — compound variants disrupt calcium-mediated gene expression critical for synaptic plasticity.",
      "CACNA1C+CACNB2": "Alpha and beta calcium channel subunits form functional complexes — variants in both compound-impair channel gating and neuronal excitability.",
      "GRM5+GRIN2A": "mGluR5 potentiates NMDA receptor currents — compound variants may synergistically reduce glutamatergic signalling.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} glutamatergic signalling variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on excitatory neurotransmission. These variants are implicated in schizophrenia, bipolar disorder, and depression risk via calcium/glutamate signalling.",
    actionTemplates: [
      {
        priority: "consider",
        category: "monitoring",
        title: "Psychiatric symptom awareness",
        detail: "Glutamatergic pathway variants are associated with psychotic and mood disorders. Discuss family history and early warning signs with a clinician.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "GABAergic Neurotransmission",
    slug: "gaba",
    description: "Variants in GABA receptors, synthesising enzymes, and transporters affecting inhibitory neurotransmission — linked to anxiety disorders and schizophrenia.",
    genePatterns: ["GABRA1", "GABRB2", "GABRG2", "GAD1", "GAD2", "SLC6A1", "ABAT", "LHFPL3", "GPHN"],
    keywords: ["gaba", "inhibitory", "benzodiazepine", "anxiety", "interneuron"],
    categories: ["psychiatric"],
    tags: ["pathway:gaba"],
    interactionNotes: {
      "GAD1+GAD2": "GAD1 and GAD2 are the two glutamic acid decarboxylase isoforms synthesising GABA — compound variants severely reduce GABA production capacity.",
      "GABRA1+GABRG2": "GABRA1 and GABRG2 form subunits of the GABA-A receptor — compound variants alter receptor sensitivity and benzodiazepine response.",
      "GPHN+GABRA1": "Gephyrin scaffolds GABA-A receptors at inhibitory synapses — compound variants disrupt both receptor clustering and subunit function.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} GABAergic variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} inhibitory neurotransmission impact. May affect anxiety susceptibility and benzodiazepine sensitivity.",
    actionTemplates: [
      {
        priority: "consider",
        category: "monitoring",
        title: "Anxiety and inhibitory tone awareness",
        detail: "GABAergic variants may increase susceptibility to anxiety disorders. Consider anxiety screening and discuss benzodiazepine sensitivity with prescribers.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "HPA Axis / Stress Response",
    slug: "hpa-axis",
    description: "Variants in the hypothalamic-pituitary-adrenal axis affecting cortisol regulation and stress response — linked to PTSD, depression, and anxiety.",
    genePatterns: ["CRHR1", "CRHR2", "NR3C1", "NR3C2", "FKBP5", "CRH", "POMC", "AVP"],
    keywords: ["cortisol", "stress", "hpa", "glucocorticoid", "ptsd", "corticotropin"],
    categories: ["psychiatric"],
    tags: ["pathway:hpa-axis"],
    interactionNotes: {
      "FKBP5+NR3C1": "FKBP5 regulates glucocorticoid receptor (NR3C1) sensitivity — compound variants create a feed-forward loop of cortisol dysregulation.",
      "CRHR1+CRH": "CRH activates CRHR1 to initiate the stress response — variants in both may alter stress reactivity threshold and recovery.",
      "NR3C1+NR3C2": "Glucocorticoid and mineralocorticoid receptors jointly regulate HPA axis feedback — compound variants impair cortisol homeostasis.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} HPA axis variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} stress response regulation. May affect susceptibility to PTSD, depression, and anxiety under chronic stress.",
    actionTemplates: [
      {
        priority: "consider",
        category: "lifestyle",
        title: "Stress management and resilience building",
        detail: "HPA axis variants may increase vulnerability to stress-related disorders. Consider proactive stress management, mindfulness practices, and early intervention after traumatic events.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Synaptic Plasticity / Neurodevelopment",
    slug: "synaptic-plasticity",
    description: "Variants in synaptic adhesion molecules, scaffolding proteins, and neurodevelopmental regulators — implicated in autism, schizophrenia, and ADHD.",
    genePatterns: ["NRXN1", "NRXN3", "NLGN3", "NLGN4X", "SHANK2", "SHANK3", "CNTNAP2", "CHD8", "DISC1", "DTNBP1", "NRG1", "NEGR1", "FOXP2", "SEMA6D", "PCDH7", "ANK3", "ODZ4", "RIMS1"],
    keywords: ["synapse", "plasticity", "neurodevelopmental", "autism", "synaptic", "adhesion", "axon guidance", "neurexin"],
    categories: ["psychiatric"],
    tags: ["pathway:synaptic-plasticity"],
    interactionNotes: {
      "NRXN1+NLGN3": "Neurexins and neuroligins form trans-synaptic complexes — compound variants disrupt both pre- and post-synaptic organisation.",
      "SHANK2+SHANK3": "Both SHANK proteins scaffold excitatory postsynaptic densities — compound variants severely impair glutamatergic synapse function.",
      "DISC1+NRG1": "DISC1 and NRG1 converge on ErbB signalling and cortical development — compound variants compound neurodevelopmental risk for psychosis.",
      "ANK3+CACNA1C": "Ankyrin-G anchors ion channels at the axon initial segment — variants with calcium channel genes compound neuronal excitability deficits.",
    },
    synergyMultiplier: 1.4,
    homozygousPenalty: 1.6,
    narrativeTemplate: "{{variantCount}} synaptic plasticity / neurodevelopment variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} impact on synaptic function and brain development. These variants span multiple psychiatric conditions including autism, schizophrenia, and ADHD.",
    actionTemplates: [
      {
        priority: "consider",
        category: "screening",
        title: "Neurodevelopmental and psychiatric assessment",
        detail: "Multiple synaptic/neurodevelopmental variants detected. Consider neurodevelopmental screening if symptomatic, and discuss family history with a clinician.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "Neuroimmune / Complement",
    slug: "neuroinflammation",
    description: "Variants in complement, MHC, and inflammatory genes affecting neuroimmune function — strongly implicated in schizophrenia (C4A) and bipolar disorder.",
    genePatterns: ["C4A", "C4B", "HLA-DRB1", "HLA-B", "IL6", "TNF", "MIF", "NFKB1", "TLR4", "TRIM26", "CEBPB", "ITIH3"],
    keywords: ["neuroinflammation", "complement", "microglia", "c4", "mhc", "immune", "cytokine"],
    categories: ["psychiatric"],
    tags: ["pathway:neuroinflammation"],
    interactionNotes: {
      "C4A+HLA-B": "C4A drives excessive synaptic pruning via microglia; HLA-B modulates antigen presentation in the brain — compound MHC variants implicate adaptive and innate neuroimmunity.",
      "IL6+TNF": "IL6 and TNF are pro-inflammatory cytokines elevated in psychosis and depression — compound variants may amplify neuroinflammatory responses.",
      "C4A+TRIM26": "Both are MHC region genes — compound variants increase schizophrenia risk through excessive complement-mediated synaptic elimination during adolescence.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} neuroimmune variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} neuroinflammatory risk. The complement system (particularly C4A) is the strongest genetic finding in schizophrenia, driving excessive synaptic pruning.",
    actionTemplates: [
      {
        priority: "consider",
        category: "monitoring",
        title: "Neuroimmune and inflammatory markers",
        detail: "Neuroimmune variants may increase susceptibility to psychotic disorders. Consider inflammatory marker monitoring (CRP, IL-6) and discuss with a psychiatrist if symptomatic.",
        minRiskLevel: "moderate",
      },
    ],
  },

  // ─── Detoxification / Pharmacogenomics ──────────────────────
  {
    name: "Phase I Detoxification (CYP450)",
    slug: "detox-phase1",
    description: "Cytochrome P450 enzyme variants that affect Phase I drug metabolism, activating or deactivating medications and environmental toxins.",
    genePatterns: ["CYP2D6", "CYP2C19", "CYP2C9", "CYP3A4", "CYP3A5", "CYP1A2", "CYP2B6", "CYP2A6", "CYP1B1"],
    keywords: ["metabolizer", "cyp450", "cytochrome", "drug metabolism"],
    categories: ["pharmacogenomics"],
    tags: ["pathway:detox-phase1"],
    interactionNotes: {
      "CYP2D6+CYP2C19": "Many drugs are metabolised by both enzymes — compound poor-metaboliser status narrows the safe medication list dramatically.",
      "CYP2C9+CYP2C19": "Adjacent CYP2C genes share substrates — compound variants affect warfarin, clopidogrel, and NSAID metabolism.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} Phase I CYP450 variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100. These variants affect metabolism of a wide range of medications. Pharmacist consultation essential before new prescriptions.",
    actionTemplates: [
      {
        priority: "urgent",
        category: "pharmacogenomics",
        title: "Create pharmacogenomics alert card",
        detail: "CYP450 variants significantly affect drug metabolism. Carry metaboliser status information for healthcare encounters.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Phase II Conjugation",
    slug: "detox-phase2",
    description: "Variants in Phase II conjugation enzymes (glucuronidation, acetylation, glutathione conjugation) that affect drug clearance and toxin elimination.",
    genePatterns: ["NAT2", "UGT1A1", "GSTP1", "GSTM1", "GSTT1", "TPMT", "SULT1A1"],
    keywords: ["conjugation", "glucuronidation", "acetylation", "glutathione"],
    categories: [],
    tags: ["pathway:detox-phase2"],
    interactionNotes: {
      "NAT2+GSTP1": "NAT2 acetylates aromatic amines; GSTP1 conjugates electrophilic metabolites — compound slow variants impair elimination of carcinogenic intermediates.",
      "UGT1A1+GSTP1": "UGT1A1 glucuronidates bilirubin and drugs; GSTP1 handles reactive metabolites — double impairment reduces detox capacity broadly.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} Phase II conjugation variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} Phase II detoxification capacity. May affect drug clearance and environmental toxin elimination.",
    actionTemplates: [
      {
        priority: "consider",
        category: "pharmacogenomics",
        title: "Phase II enzyme awareness for prescribing",
        detail: "Slow conjugation may affect clearance of specific drugs. Flag for pharmacist review.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Drug Transport / Efflux",
    slug: "drug-transport",
    description: "Variants in membrane transporters that control drug absorption, distribution, and excretion — affecting bioavailability and tissue exposure.",
    genePatterns: ["ABCB1", "ABCG2", "SLCO1B1", "SLC22A1", "SLC15A1"],
    keywords: ["p-glycoprotein", "drug transport", "efflux", "statin myopathy", "oatp"],
    categories: [],
    tags: ["pathway:drug-transport"],
    interactionNotes: {
      "ABCB1+SLCO1B1": "P-gp (ABCB1) controls gut absorption and BBB efflux while OATP1B1 (SLCO1B1) handles hepatic uptake — compound variants alter tissue-specific drug levels unpredictably.",
    },
    synergyMultiplier: 1.25,
    homozygousPenalty: 1.4,
    narrativeTemplate: "{{variantCount}} drug transport variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100. Drug transporter variants affect bioavailability and tissue distribution of many medications including statins, digoxin, and chemotherapy agents.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "pharmacogenomics",
        title: "Statin and drug transporter review",
        detail: "SLCO1B1 variants increase statin myopathy risk. ABCB1 variants affect multiple drug classes. Pharmacist review recommended.",
        minRiskLevel: "moderate",
      },
    ],
  },

  // ─── Signaling Pathways ─────────────────────────────────────
  {
    name: "Wnt Signaling",
    slug: "wnt",
    description: "Variants in the Wnt/β-catenin pathway affecting cell proliferation, stem cell maintenance, and tissue homeostasis — implicated in colorectal cancer and bone density.",
    genePatterns: ["TCF7L2", "APC", "AXIN1", "AXIN2", "CTNNB1", "WNT", "LRP5", "LRP6", "DKK1", "SFRP"],
    keywords: ["wnt", "beta-catenin", "colorectal", "adenomatous polyposis"],
    categories: [],
    tags: ["pathway:wnt"],
    interactionNotes: {
      "APC+AXIN1": "Both are destruction complex components for β-catenin — compound loss-of-function dramatically increases Wnt signalling and colorectal cancer risk.",
      "TCF7L2+APC": "TCF7L2 is the Wnt transcription factor; APC regulates β-catenin levels — compound variants amplify Wnt target gene expression.",
    },
    synergyMultiplier: 1.4,
    homozygousPenalty: 1.6,
    narrativeTemplate: "{{variantCount}} Wnt signalling variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} Wnt pathway activation. This pathway affects colorectal cancer risk and bone metabolism.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Colonoscopy screening (consider earlier initiation)",
        detail: "Wnt pathway variants may warrant earlier or more frequent colorectal cancer screening. Discuss with gastroenterologist.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "DNA Damage Repair",
    slug: "dna-repair",
    description: "Variants in homologous recombination, mismatch repair, and nucleotide excision repair genes that affect genomic stability and cancer susceptibility.",
    genePatterns: ["BRCA1", "BRCA2", "PALB2", "RAD51", "CHEK2", "TP53", "ATM", "NBN", "ERCC", "MLH1", "MSH2", "MSH6", "PMS2", "MUTYH"],
    keywords: ["dna repair", "homologous recombination", "mismatch repair", "brca", "genomic instability"],
    categories: ["oncology"],
    tags: ["pathway:dna-repair"],
    interactionNotes: {
      "BRCA1+CHEK2": "CHEK2 activates BRCA1 in the DNA damage response — variants in both severely impair double-strand break repair.",
      "BRCA2+PALB2": "PALB2 recruits BRCA2 to DNA damage sites — compound variants eliminate the PALB2-BRCA2 repair axis.",
      "MLH1+MSH2": "Core mismatch repair heterodimer — compound variants cause Lynch syndrome with dramatically elevated cancer risk.",
      "ATM+TP53": "ATM activates p53 in response to DNA damage — compound variants impair both damage sensing and cell cycle arrest.",
    },
    synergyMultiplier: 1.5,
    homozygousPenalty: 2.0,
    narrativeTemplate: "{{variantCount}} DNA repair pathway variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} genomic instability risk. Genetic counselling strongly recommended for high-penetrance variants.",
    actionTemplates: [
      {
        priority: "urgent",
        category: "screening",
        title: "Genetic counselling for cancer predisposition",
        detail: "DNA repair variants may warrant enhanced cancer surveillance. Clinical-grade confirmatory testing recommended.",
        minRiskLevel: "elevated",
      },
    ],
  },

  // ─── Organ-specific ─────────────────────────────────────────
  {
    name: "Macular Degeneration / Vision",
    slug: "amd",
    description: "Variants in complement activation, angiogenesis, and extracellular matrix genes affecting age-related macular degeneration risk.",
    genePatterns: ["CFH", "ARMS2", "HTRA1", "C3", "C2", "CFB", "VEGFA", "TIMP3"],
    keywords: ["macular", "glaucoma", "amd", "vision", "retinal"],
    categories: ["ophthalmological"],
    tags: ["pathway:amd"],
    interactionNotes: {
      "CFH+ARMS2": "CFH regulates complement activation while ARMS2/HTRA1 affects mitochondrial function in RPE — combined variants attack retinal health from two angles.",
      "CFH+C3": "Both are complement pathway components — compound variants cause excessive complement-mediated retinal inflammation.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} macular degeneration pathway variant(s) ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} AMD risk. Regular dilated eye exams recommended, especially after age 50.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Annual dilated eye examination",
        detail: "Multiple AMD risk variants warrant regular ophthalmological surveillance. AREDS2 supplementation may be discussed.",
        minRiskLevel: "moderate",
      },
    ],
  },
  {
    name: "Liver / Hepatic",
    slug: "liver",
    description: "Variants affecting hepatic lipid handling, bilirubin conjugation, and liver fibrosis susceptibility.",
    genePatterns: ["PNPLA3", "TM6SF2", "UGT1A1", "HSD17B13", "MBOAT7", "GCKR", "SERPINA1"],
    keywords: ["liver", "nafld", "nash", "hepatic", "gilbert", "cirrhosis", "fibrosis"],
    categories: ["hepatic"],
    tags: ["pathway:liver"],
    interactionNotes: {
      "PNPLA3+TM6SF2": "Both affect hepatic lipid droplet remodelling — compound variants dramatically increase NAFLD/NASH progression risk.",
      "PNPLA3+HSD17B13": "HSD17B13 loss-of-function is protective against PNPLA3-driven steatosis — check if protective variant is present.",
    },
    synergyMultiplier: 1.35,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} hepatic pathway variant(s) detected ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} liver disease susceptibility. Liver function monitoring and hepatic ultrasound may be warranted.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Liver function panel and FibroScan",
        detail: "Multiple hepatic variants warrant baseline liver assessment, especially with alcohol use or metabolic risk factors.",
        minRiskLevel: "elevated",
      },
    ],
  },
  {
    name: "Pulmonary / Airway",
    slug: "pulmonary",
    description: "Variants affecting airway function, lung development, and pulmonary disease susceptibility.",
    genePatterns: ["CFTR", "CHRNA3", "CHRNA5", "CAV1", "HHIP", "FAM13A", "TGFB", "MUC5B", "SERPINA1"],
    keywords: ["pulmonary", "lung", "copd", "asthma", "cystic fibrosis", "pulmonary fibrosis"],
    categories: ["pulmonary"],
    tags: ["pathway:pulmonary"],
    interactionNotes: {
      "CHRNA3+CHRNA5": "Adjacent nicotinic receptor subunit genes — compound variants increase nicotine dependence and lung cancer susceptibility synergistically.",
      "SERPINA1+HHIP": "Alpha-1 antitrypsin deficiency combined with HHIP variants accelerates emphysema development.",
    },
    synergyMultiplier: 1.3,
    homozygousPenalty: 1.5,
    narrativeTemplate: "{{variantCount}} pulmonary pathway variant(s) identified ({{geneList}}), {{homCount}} homozygous. {{compoundEffects}}Score: {{synergyScore}}/100 — {{riskLabel}} pulmonary risk. Avoid smoking and environmental lung irritants.",
    actionTemplates: [
      {
        priority: "recommended",
        category: "screening",
        title: "Baseline pulmonary function testing",
        detail: "Multiple pulmonary variants warrant spirometry, especially if symptomatic or with smoking history.",
        minRiskLevel: "elevated",
      },
    ],
  },
];
